-- ==================================================
-- SISTEMA DE SUPLEMENTOS - ALIMETRIA
-- Script 2: Datos Iniciales
-- ==================================================

-- INSERTAR CATEGORÍAS DE SUPLEMENTOS
INSERT INTO categorias_suplementos (nombre, descripcion, color, icono, orden_visualizacion) VALUES
('Vitaminas', 'Vitaminas esenciales y complejos vitamínicos', '#FF6B6B', '🌈', 1),
('Minerales', 'Minerales y oligoelementos esenciales', '#4ECDC4', '⚡', 2),
('Proteínas', 'Suplementos proteicos y aminoácidos', '#45B7D1', '🥩', 3),
('Ácidos Grasos', 'Omega 3, 6, 9 y otros ácidos grasos esenciales', '#96CEB4', '🐟', 4),
('Probióticos', 'Microorganismos beneficiosos para la salud intestinal', '#FFEAA7', '💚', 5),
('Articular', 'Suplementos para la salud articular y ósea', '#DDA0DD', '🦴', 6),
('Deportivos', 'Suplementos específicos para deportistas', '#FFB347', '💪', 7),
('Antioxidantes', 'Compuestos antioxidantes y anti-envejecimiento', '#98D8C8', '🛡️', 8);

-- INSERTAR SUPLEMENTOS BASE (Los 10 principales de tu guía)
INSERT INTO suplementos (
    nombre, 
    categoria_id, 
    descripcion_corta, 
    descripcion_detallada,
    para_que_sirve, 
    beneficios_principales,
    dosis_recomendada, 
    forma_presentacion, 
    frecuencia_recomendada,
    mejor_momento_toma,
    duracion_tratamiento_tipica,
    nivel_evidencia,
    destacado,
    popularidad_uso
) VALUES
(
    'Multivitamínicos', 
    1, 
    'Combinación de vitaminas y minerales esenciales en una sola fórmula',
    'Los multivitamínicos son suplementos que contienen una combinación de vitaminas y minerales esenciales que el cuerpo necesita para funcionar correctamente. Están diseñados para complementar la dieta cuando no se obtienen suficientes nutrientes de los alimentos.',
    'Personas con dietas poco equilibradas, adultos mayores, pacientes en recuperación, personas con restricciones alimentarias',
    '["Corrige deficiencias nutricionales", "Mejora energía y vitalidad", "Apoya sistema inmune", "Facilita metabolismo celular", "Previene anemias por deficiencia"]',
    '1 tableta al día con la comida principal', 
    'tableta', 
    '1 vez al día',
    'Con desayuno o almuerzo',
    'Uso continuo',
    'alta',
    1,
    85
),
(
    'Vitamina D3', 
    1, 
    'Vitamina esencial para la salud ósea, sistema inmune y regulación hormonal',
    'La vitamina D3 (colecalciferol) es crucial para la absorción de calcio, el fortalecimiento óseo y tiene funciones importantes en el sistema inmune y la regulación hormonal. La deficiencia es muy común debido a la falta de exposición solar.',
    'Deficiencia muy común en adultos, personas con poca exposición solar, osteoporosis, síndrome metabólico',
    '["Fortalece huesos y dientes", "Mejora absorción de calcio", "Apoya sistema inmunológico", "Regula estado de ánimo", "Previene osteoporosis"]',
    '1000-4000 UI por día (según niveles en sangre)', 
    'cápsula', 
    '1 vez al día',
    'Con una comida que contenga grasas',
    'Uso continuo con monitoreo',
    'alta',
    1,
    92
),
(
    'Omega 3 (EPA/DHA)', 
    4, 
    'Ácidos grasos esenciales para la salud cardiovascular, función cerebral y control de inflamación',
    'Los ácidos grasos Omega 3, especialmente EPA y DHA, son fundamentales para la salud cardiovascular, función cerebral, desarrollo ocular y control de procesos inflamatorios. El cuerpo no puede producirlos, por lo que deben obtenerse de la dieta o suplementación.',
    'Hipercolesterolemia, triglicéridos altos, riesgo cardiovascular, deportistas, función cognitiva, inflamación crónica',
    '["Reduce colesterol y triglicéridos", "Protege corazón y arterias", "Mejora función cerebral", "Reduce inflamación", "Apoya salud ocular", "Mejora estado de ánimo"]',
    '1-3 gramos de EPA/DHA por día', 
    'cápsula', 
    '1-2 veces al día',
    'Con las comidas principales',
    'Uso continuo',
    'alta',
    1,
    98
),
(
    'Proteína en Polvo', 
    3, 
    'Suplemento proteico para construcción y reparación muscular',
    'Las proteínas en polvo (suero, vegetal, caseína) proporcionan aminoácidos esenciales necesarios para la síntesis de proteínas musculares, recuperación post-ejercicio y mantenimiento de masa muscular, especialmente útil cuando la ingesta dietética es insuficiente.',
    'Deportistas, pacientes con sarcopenia, recuperación post-quirúrgica, adultos mayores, dietas hiperproteicas',
    '["Construye y repara músculos", "Acelera recuperación post-ejercicio", "Mantiene masa muscular", "Facilita pérdida de grasa", "Mejora composición corporal"]',
    '25-50 gramos por porción (1-2 porciones/día)', 
    'polvo', 
    '1-3 veces al día',
    'Post-entreno y entre comidas',
    'Según objetivos (3-6 meses típico)',
    'alta',
    1,
    76
),
(
    'Calcio', 
    2, 
    'Mineral esencial para la salud ósea, muscular y función nerviosa',
    'El calcio es el mineral más abundante en el cuerpo y es fundamental para la formación y mantenimiento de huesos y dientes. También juega roles críticos en la contracción muscular, función nerviosa y coagulación sanguínea.',
    'Osteopenia, osteoporosis, mujeres postmenopáusicas, adolescentes en crecimiento, deficiencia dietética',
    '["Fortalece huesos y dientes", "Previene osteoporosis", "Mejora contracción muscular", "Apoya función nerviosa", "Ayuda en coagulación"]',
    '500-1200 mg por día (según edad y sexo)', 
    'tableta', 
    '2-3 veces al día',
    'Con comidas para mejor absorción',
    'Uso continuo',
    'alta',
    0,
    54
),
(
    'Hierro', 
    2, 
    'Mineral esencial para la prevención y tratamiento de anemia ferropénica',
    'El hierro es crucial para la formación de hemoglobina y el transporte de oxígeno en sangre. La deficiencia de hierro es una de las carencias nutricionales más comunes, especialmente en mujeres en edad fértil.',
    'Mujeres en edad fértil, embarazadas, vegetarianos estrictos, anemia ferropénica, donantes frecuentes de sangre',
    '["Previene y trata anemia", "Mejora transporte de oxígeno", "Reduce fatiga y cansancio", "Apoya función cognitiva", "Fortalece sistema inmune"]',
    '18-65 mg por día (según deficiencia)', 
    'tableta', 
    '1 vez al día',
    'En ayunas o con vitamina C',
    '3-6 meses bajo supervisión',
    'alta',
    0,
    67
),
(
    'Probióticos', 
    5, 
    'Bacterias beneficiosas para el equilibrio de la microbiota intestinal',
    'Los probióticos son microorganismos vivos que, cuando se administran en cantidades adecuadas, confieren beneficios para la salud del huésped, principalmente mejorando el equilibrio de la microbiota intestinal.',
    'Disbiosis intestinal, post-tratamiento antibiótico, síndrome de intestino irritable, diarreas, apoyo inmunológico',
    '["Equilibra microbiota intestinal", "Mejora digestión", "Fortalece sistema inmune", "Reduce inflamación intestinal", "Previene diarreas"]',
    '1-10 billones de UFC por día', 
    'cápsula', 
    '1-2 veces al día',
    'Con o sin comida (según cepa)',
    '4-8 semanas iniciales',
    'media',
    1,
    71
),
(
    'Colágeno Hidrolizado', 
    6, 
    'Proteína específica para la salud articular, piel y tejidos conectivos',
    'El colágeno hidrolizado es una forma procesada de colágeno que se absorbe más fácilmente. Es la proteína más abundante en el cuerpo y componente principal de cartílagos, huesos, piel, tendones y ligamentos.',
    'Artritis, desgaste articular, envejecimiento de la piel, recuperación de lesiones, estética anti-edad',
    '["Mejora salud articular", "Reduce dolor artrítico", "Fortalece piel y cabello", "Acelera cicatrización", "Mantiene elasticidad"]',
    '10-20 gramos por día', 
    'polvo', 
    '1 vez al día',
    'En ayunas o antes de dormir',
    'Mínimo 3 meses para ver efectos',
    'media',
    0,
    43
),
(
    'Creatina', 
    7, 
    'Compuesto que aumenta la fuerza, potencia y rendimiento muscular',
    'La creatina es un compuesto natural que se encuentra en los músculos y ayuda a producir energía durante ejercicios de alta intensidad. Es uno de los suplementos deportivos más estudiados y efectivos.',
    'Deportistas, entrenamiento de fuerza, adultos mayores con pérdida de masa muscular, deportes explosivos',
    '["Aumenta fuerza y potencia", "Mejora rendimiento anaeróbico", "Acelera recuperación", "Incrementa masa muscular", "Mejora función cognitiva"]',
    '3-5 gramos por día', 
    'polvo', 
    '1 vez al día',
    'Post-entreno o cualquier momento',
    'Uso continuo durante entrenamientos',
    'alta',
    1,
    88
),
(
    'BCAA (Aminoácidos Ramificados)', 
    3, 
    'Aminoácidos esenciales que disminuyen la fatiga muscular y favorecen la recuperación',
    'Los BCAA (Leucina, Isoleucina, Valina) son aminoácidos esenciales que el cuerpo no puede producir. Son especialmente importantes para la síntesis de proteínas musculares y pueden reducir la fatiga durante el ejercicio.',
    'Deportistas en entrenamientos intensos, personas con dietas bajas en proteína, ejercicios de resistencia prolongados',
    '["Reduce fatiga muscular", "Acelera recuperación", "Previene catabolismo", "Mejora resistencia", "Apoya síntesis proteica"]',
    '5-15 gramos por día (2:1:1 ratio)', 
    'polvo', 
    '2-3 veces al día',
    'Antes, durante y post-entreno',
    'Durante períodos de entrenamiento intenso',
    'media',
    0,
    39
);
